"""Initial migration

Revision ID: 1093a1e49a0d
Revises: 
Create Date: 2025-07-18 16:06:40.337144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1093a1e49a0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archetypes',
    sa.Column('archetype_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='telegram user id'),
    sa.PrimaryKeyConstraint('archetype_id')
    )
    op.create_table('styles',
    sa.Column('style_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='telegram user id'),
    sa.PrimaryKeyConstraint('style_id')
    )
    op.create_table('characters',
    sa.Column('character_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='telegram user id'),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetypes.archetype_id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.style_id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_table('styles')
    op.drop_table('archetypes')
    # ### end Alembic commands ###
