"""Initial migration

Revision ID: 258b497c184d
Revises: d1a7247f9acc
Create Date: 2025-07-18 16:21:22.245615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258b497c184d'
down_revision: Union[str, Sequence[str], None] = 'd1a7247f9acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archetypes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='telegram user id')
    op.alter_column('characters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='telegram user id')
    op.alter_column('styles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='telegram user id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('styles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='telegram user id')
    op.alter_column('characters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='telegram user id')
    op.alter_column('archetypes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='telegram user id')
    # ### end Alembic commands ###
