"""Initial migration

Revision ID: d1a7247f9acc
Revises: 1093a1e49a0d
Create Date: 2025-07-18 16:07:20.956524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a7247f9acc'
down_revision: Union[str, Sequence[str], None] = '1093a1e49a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archetypes', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archetypes', 'description')
    # ### end Alembic commands ###
